# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PDFPrePractice' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'RxSwift'
pod 'RxCocoa'
pod 'CTMediator'
pod 'Alamofire'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'Kingfisher'
pod 'SwiftyBeaver'

  # Pods for PDFPrePractice

end
